[project]
name = "sam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "nats-py>=2.10.0",
    "pydantic>=2.11.7",
    "pymongo>=4.13.2",
    "strawberry-graphql[fastapi]>=0.275.5",
]
