services:

  mongo:
    image: mongo
    restart: always
    container_name: labeling-app-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017

  backend-app:
    image: ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/auto-labeling-app/backend-app:${TAG:-latest}
    build:
      context: backend/app
      dockerfile: Dockerfile
    container_name: labeling-app-backend
    ports:
      - 8000:80
    depends_on:
      - mongo
    secrets:
      - gcp_service_account
      - clerk_jwt_public
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_service_account
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      CLERK_JWT_PUB_KEY: /run/secrets/clerk_jwt_public
    env_file:
      - backend/app/dev.env
    volumes:
      - ./backend/app:/app
      - /app/.venv
    command: /app/.venv/bin/fastapi run main.py --port 80 --host 0.0.0.0 --reload
    develop:
      watch:
        - action: sync
          path: .
          target: backend/app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml

  nats:
    image: nats:latest
    container_name: labeling-app-nats
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - ./data/nats:/data/nats

  models-gateway:
    image: ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/auto-labeling-app/models-gateway:${TAG:-latest}
    build:
      context: models/gateway
      dockerfile: Dockerfile
    container_name: labeling-app-models-gateway
    command: /app/.venv/bin/fastapi run main.py --port 80 --host 0.0.0.0 --reload
    depends_on:
      - nats
    ports:
      - 8080:80
    volumes:
      - ./models/gateway:/app
      - /app/.venv
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017

  models-sam:
    image: ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/auto-labeling-app/models-sam:${TAG:-latest}
    build:
      context: models/sam
      dockerfile: Dockerfile
    container_name: labeling-app-models-sam
    depends_on:
      - nats
    environment:
      NATS_URL: nats://nats:4222

  models-yolo:
    image: ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/auto-labeling-app/models-yolo:${TAG:-latest}
    build:
      context: models/yolo
      dockerfile: Dockerfile
    container_name: labeling-app-models-yolo
    depends_on:
      - nats
    environment:
      NATS_URL: nats://nats:4222
      MONGO_URL: mongodb://root:example@mongo:27017

secrets:
  gcp_service_account:
    file: backend/app/gcp_service_account.json
  clerk_jwt_public:
    file: backend/app/jwt_public.pem
