env:
  PROJECT_ID: 'probable-willow-464616-k2'  # Updated project ID
  REGION: 'asia-east1'
  SERVICE: 'backend-app'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/404276494097/locations/global/workloadIdentityPools/'  # Update this as well

# ... existing code ...
      - name: 'Build and Push Image'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/auto-labeling-app/${{ env.SERVICE }}:${{ env.TAG }}" 
          docker build --tag "${DOCKER_TAG}" backend/app
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/auto-labeling-app/${{ env.SERVICE }}:${{ env.TAG }}'
# ... existing code ... 