[project]
name = "gateway"
version = "0.1.0"
description = "SAM model"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nats-py>=2.10.0",
    "pydantic>=2.11.7",
    "ultralytics>=8.3.162",
]
