name: 'Build and deploy models YOLOWorld'


on:
  push:
    branches:
      - main
    paths:
      - 'models/yolo/**'

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}


jobs:
  build-and-push:
    runs-on: 'ubuntu-latest'

    permissions:
        contents: 'read'
        id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2' # google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'github-deploy@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.GCP_REGION }}-docker.pkg.dev'

      - name : Add SHORT_SHA Environment Variable as TAG
        id   : short-sha
        shell: bash
        run  : echo "TAG=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      # Somehow `docker compose push` need env_file, so we create one as workaround
      - name: 'Create dummy env for push'
        run: |-
          touch backend/app/dev.env

      - name: 'Build and Push Image'
        run: |-
          docker compose build models-yolo
          docker compose push models-yolo
